name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**Dockerfile'

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:

      - name: Install Node.js
        run: |
          apk add --no-cache nodejs npm

      - name: Install docker-cli
        run: |
          apk add --no-cache docker-cli

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: git.amellado.stream
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed Dockerfiles
        id: get_changed
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Dockerfile$' > changed_dockerfiles.txt
          echo "Changed Dockerfiles:"
          cat changed_dockerfiles.txt

      - name: Build and push
        run: |
          REPO_URL="${{ github.server_url }}/${{ github.repository }}.git"
          BRANCH="main"

          while read -r dockerfile; do
            [ -z "$dockerfile" ] && continue
            dir=$(dirname "$dockerfile")
            name=$(echo "$dir" | tr '/' '-')
            version=$(cat "$dockerfile" | grep -i "ARG $name_VERSION" | cut -d= -f2)

            docker buildx build \
              --cache-to=type=registry,ref=git.amellado.stream/cache,mode=max \
              --cache-from=type=registry,ref=git.amellado.stream/cache \
              --progress plain \
              --file "$dockerfile" \
              --tag "git.amellado.stream/davidfdezalcoba/${name}:${version}" \
              --push \
              ./${name}
          done < changed_dockerfiles.txt
